In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("POI_den.csv",header=0)

In [3]:
df.head()

   type  TAZID  count
0     5   1054     58
1     3   1054    586
2     6   1054     53
3     2   1054    239
4     1   1054    346

In [4]:
id = df.TAZID.max()

In [5]:
DEN_numpy = np.array(df)
len = DEN_numpy.shape[0]

In [6]:
INFO = pd.read_csv("Shenzhen_Pile_Information.csv",header=0)
INFO.head()

   NO  grid  count  fast_count  slow_count
0   0   102     30           3          27
1   1   105     93           0          93
2   2   107     88           2          86
3   3   108     39           0          39
4   4   109     39           0          39

In [7]:
new_numpy = np.zeros((int(id)+1, 15))

In [8]:
for i in range(len):
    r_type = DEN_numpy[i,0]
    r_id = DEN_numpy[i,1]
    new_numpy[int(r_id), int(r_type)] = DEN_numpy[i,2]
for i in range(int(id)+1):
    new_numpy[i, 0] = i

In [9]:
new_list_2 = []
for i in range(INFO.shape[0]):
    new_list_2.append(new_numpy[INFO["grid"][i]])

In [10]:
new_df = pd.DataFrame(data=new_list_2, columns=["TAZID","1","2","3","4","5","6","7","8","9","10","11","12","13","14"])

In [11]:
new_df.to_csv("SZ_area_POI.csv")